#Hamoye Stage A Data Science Internship Quiz

Hamoye Stage A Data Science Internship Quiz
Hi, I am Adarsh Dhir, Data Science Intern at Hamoye AI. Below is my Answers to Quiz Stage A on the fuel data set :

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
df.head(10)

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570
5  f1_fuel_1994_12_2_0_13  ...                1.850
6   f1_fuel_1994_12_2_1_1  ...                0.450
7  f1_fuel_1994_12_2_1_10  ...                2.360
8  f1_fuel_1994_12_2_2_10  ...                1.400
9   f1_fuel_1994_12_4_0_1  ...                1.278

[10 rows x 11 columns]

**Ques-1**

In [11]:
A =[1,2,3,4,5,6]
B =[13,21,34]
A.extend(B)
A_B=A
print("extended array", A_B)

A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.append(B)
print("appended array",A)

extended array [1, 2, 3, 4, 5, 6, 13, 21, 34]
appended array [1, 2, 3, 4, 5, 6, [13, 21, 34]]


**Ques-2**

In [13]:
print(np.array([[1,0,0],[0,1,0],[0,0,1]]),"\n")
print(np.eye(3),"\n")
print(np.identity(3),"\n")

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



**Ques-3**

In [ ]:
df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

Observation : gas fuel type has lowest average fuel cost per unit burned

**Ques-4**

In [15]:
desc_data=df['fuel_mmbtu_per_unit'].describe()
print('standard deviation : ',desc_data['std'].round(2))
print('75th percentile : ',desc_data['75%'].round(2))


standard deviation :  10.6
75th percentile :  17.01


**Ques-5**

In [16]:

print("skewness : ",df['fuel_qty_burned'].skew().round(2))
print("kurtosis : ",df['fuel_qty_burned'].kurtosis().round(2))

skewness :  15.85
kurtosis :  651.37


**Ques-6**

In [ ]:
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

Observation: fuel_unit has 180 missing values

In [17]:
print("Percentage missing : ",sum((df.isnull().sum()*100)/len(df)))

Percentage missing :  0.6096941367747181


**Ques-7**

In [19]:
df.dtypes

record_id                        object
utility_id_ferc1                  int64
report_year                       int64
plant_name_ferc1                 object
fuel_type_code_pudl              object
fuel_unit                        object
fuel_qty_burned                 float64
fuel_mmbtu_per_unit             float64
fuel_cost_per_unit_burned       float64
fuel_cost_per_unit_delivered    float64
fuel_cost_per_mmbtu             float64
dtype: object

Observation: fuel_unit is a dtype 'object', hence its a categorial variable and we will use mode imputation for missing values.

**Ques-8**

In [20]:
abs(df.corrwith(df['fuel_cost_per_unit_burned'])).sort_values()

fuel_cost_per_mmbtu             0.000437
fuel_mmbtu_per_unit             0.010034
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_qty_burned                 0.018535
utility_id_ferc1                0.037863
fuel_cost_per_unit_burned       1.000000
dtype: float64

Obeservation: 'Fuel_mmbtu_per_unit' and 'fuel_cost_per_unit_delivered' has the second and third lowest correlation with the 'fuel_cost_per_unit_burned' respectively.

**Ques-9**

In [22]:
coal_data=df[df['fuel_type_code_pudl']=='coal']

year_1994=coal_data[coal_data['report_year']==1994]['fuel_cost_per_unit_burned'].sum()
year_1998=coal_data[coal_data['report_year']==1998]['fuel_cost_per_unit_burned'].sum()

percent_change=(((year_1998-year_1994)/year_1994)*100).round()

print("Percentage Change : "+str(int(percent_change))+"%")

Percentage Change : -21%


**Ques-10**

In [23]:
df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean().sort_values(ascending=False)

report_year
1997    11140.197239
1996     9196.705948
2000      985.362877
2009      652.694163
2018      499.269966
2015      326.535511
1998      287.154420
2014      192.737183
2013      172.307591
2004      139.524275
2016      103.901761
2010       91.862105
1994       63.636060
2012       60.994502
2001       60.050396
2011       59.774667
2008       58.588197
2003       55.663493
2002       47.594361
2017       46.196861
2007       43.325023
2005       41.438184
2006       38.657484
1995       32.735269
1999       25.551627
Name: fuel_cost_per_unit_delivered, dtype: float64

Observation : The highest average fuel cost per unit delivered is in 1997.